model:
  block_nums: 10
  input_channels: 1
  input_size: [9, 9]

optimizer:
  learning_rate: 0.02
  momentum: 0.9
  weight_decay: 1.e-4
  nesterov: True

trainer:
  batch_size: 32
  batch_to_train: 16
  checkpoint_freq: 5
  checkpoint_dir: /desktop/checkpoint/
  weight_dir: /desktop/weight/
  log_dir: /desktop/log/

replayer_buffer:
  size: 1024

game:
  board_size: 9
